# Before upgrading check that everything is available on all tier1 targets here:
# https://rust-lang.github.io/rustup-components-history
[toolchain]
channel = "nightly-2021-08-03"
components = [ "rustfmt", "rustc", "rust-src" ]
targets = [ "thumbv7em-none-eabihf", "thumbv7em-none-eabi", "thumbv6m-none-eabi" ]
